

services:
  file-transfer-intranet:
    build: .
    container_name: file_transfer_service
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - APP_USER=admin 
      - APP_PASSWORD_HASH=$$2a$$10$$vaBMvTqY1bH1xFfMtlId8Oa.//U06k3GrMvkynwBUgZiEbSEfwnwy
      - JWT_SECRET=smartly-crier6-facedown
    restart: unless-stopped